### ISSUE TITLE
Adding node pool to existing cluster fails

### ISSUE THREAD

**Issue by hansenms** [microsoft/tyger#121]
When trying to add a nodepool to an existing cluster, you get an error message like:

```
Error: failed to create cluster: PUT https://management.azure.com/subscriptions/<REDACTED>/resourceGroups/<REDACTED>/providers/Microsoft.ContainerService/managedClusters/<REDACTED>
--------------------------------------------------------------------------------
RESPONSE 400: 400 Bad Request
ERROR CODE: BadRequest
--------------------------------------------------------------------------------
{
  "code": "BadRequest",
  "details": null,
  "message": "A new agent pool was introduced. Adding agent pools to an existing cluster is not allowed through managed cluster operations. For agent pool specific change, please use per agent pool operations: https://aka.ms/agent-pool-rest-api",
  "subcode": ""
}
--------------------------------------------------------------------------------
```

**Comment by krishkalai** [comment]
Facing same issue with bicep template based deployment. 
API version used: Microsoft.ContainerService/managedClusters@2023-07-02-preview
Error message: 
"Preflight validation check for resource(s) for container service xxxxxx in resource group  xxxxxx failed. Message: A new agent pool was introduced. Adding agent pools to an existing cluster is not allowed through managed cluster operations. For agent pool specific change, please use per agent pool operations: https://aka.ms/agent-pool-rest-api. Details:  (Code: BadRequest)"

**Comment by hansenms** [comment]
@krishkalai I am assuming this is not in context of deploying Tyger? This issue should actually be closed since we have implemented a fix here.

**Comment by krishkalai** [comment]
@hansenms  his is not related to tyger. We got this issue today when we tried to add a new agent pool addition to an existing AKS managedcluster using "Microsoft.ContainerService/managedClusters@2023-07-02-preview" api version. Does this fix applies to all Api versions of managed clusters?

**Comment by johnstairs** [comment]
This was not a fix to the AKS API. It was a fix to Tyger, which deploys and uses AKS.

**Comment by krishkalai** [comment]
@johnstairs Thanks for the clarity.
